import type { Metadata } from "next";
import {
  ChevronDownIcon,
  CircleHelpIcon,
  MailIcon,
  MessageCircleReplyIcon,
} from "lucide-react";

import {
  SiteFooter,
  SiteHeader,
} from "@/components/site-chrome";

export const metadata: Metadata = {
  title: "FAQ | TownHallUS.com",
  description:
    "Frequently asked questions about TownHallUS.com accounts, political neutrality, user identity, posting, comments, and support.",
};

const highlightClassName =
  "font-semibold text-[#000000] underline decoration-[#808080] decoration-2 underline-offset-4";

const contactLinkClassName =
  "text-[#9333EA] underline decoration-[#808080] decoration-2 underline-offset-4 transition-colors hover:text-[#7E22CE] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#000000]";

const faqs: ReadonlyArray<{
  question: string;
  answer: React.ReactNode;
}> = [
  {
    question:
      "Why should we use townhallus.com for discussing American politics since there are other online platforms available?",
    answer: (
      <>
        <p>
          Other online platforms are designed for general purposes, NOT as a{" "}
          <span className={highlightClassName}>
            open, professional and neutral
          </span>{" "}
          space dedicated to American politics. They lack several key features
          that townhallus.com provides:
        </p>
        <ol className="mt-3 list-decimal space-y-2 pl-6">
          <li>
            They do{" "}
            <span className={highlightClassName}>
              NOT allow structured discussions at the state, city, and county
              levels
            </span>
            .
          </li>
          <li>
            They do{" "}
            <span className={highlightClassName}>
              NOT verify whether users are registered voters or U.S. citizens
            </span>
            .
          </li>
          <li>
            They use Artificial Intelligence to push only favorable posts, which{" "}
            <span className={highlightClassName}>
              increases political polarization
            </span>
            .
          </li>
          <li>
            Their management does{" "}
            <span className={highlightClassName}>
              Not aim for political neutrality
            </span>
            , nor do they want to be politically neutral.
          </li>
          <li>
            They are{" "}
            <span className={highlightClassName}>
              NOT continually developing features designed specifically for
              political discussions
            </span>
            .
          </li>
        </ol>
      </>
    ),
  },
  {
    question: "Which side does townhallus.com lean toward -- left or right?",
    answer: (
      <p>
        The goal of townhallus.com is to provide a{" "}
        <span className={highlightClassName}>
          open, professional and neutral
        </span>{" "}
        platform that allows Democrats, Republicans, independents, and
        non-partisans to communicate with each other. You will be exposed to
        perspectives from all sides, without the misuse of Artificial
        Intelligence that filters content to show you only favored views.
      </p>
    ),
  },
  {
    question:
      "I am an American citizen, and my age is between 13 ~ 18. I am not yet qualified to be a registered voter. Can I sign up as a user?",
    answer:
      "Yes. Please have your birth certificate ready to prove your citizenship.",
  },
  {
    question:
      "I am an American citizen. Where should I go to register as a voter before loging up as a user here?",
    answer:
      "You can register to vote on your state government's website or visit vote.com to complete your voter registration before loging up here.",
  },
  {
    question: "Can I have my own customized avatar?",
    answer:
      "Your avatar is automatically assigned based on the system-generated unique ID in our database. It does not reflect your age, gender, or appearance but is uniquely recognizable by other users without revealing your true appearance. Enjoy your masquerade party! If you'd like to display your full name, you can do so in the self-introduction section.",
  },
  {
    question: "Can I have my own customized username?",
    answer:
      "Your username is automatically generated by the system. It combines your first name, the first letter of your last name, and ten random letters or numbers. It is unique and recognizable by other users.",
  },
  {
    question: "I forgot my password. Can I reset it?",
    answer:
      "A password reset feature will be available soon. In the meantime, please use a different email address to create a new account. We periodly delete old, unused accounts.",
  },
  {
    question:
      "I had submitted the valid url of a picture and a video. Why cannot I see them anymore?",
    answer:
      "If the url is broken, our system would automatically replace them with an internal message box instead of an empty page or an error message.",
  },
  {
    question: "Can I post or comment in any other languages than English?",
    answer:
      "Please no, sorry! We do not have any resources to moderate in any other languages than English. Can you use a translation software (Perhaps, Google Translate) to translate your article into English and then post it here? Thank you!",
  },
  {
    question:
      "Why can't I find a traditional thumbs-up and thumbs-down button on the article? How can I show my appreciation for a particular post?",
    answer:
      "We believe the traditional thumbs-up and thumbs-down buttons are too simplistic and lack depth. We are developing a brand-new, multi-dimensional evaluation system on an article.",
  },
  {
    question: "Why can't I follow anyone here or be followed by someone else?",
    answer:
      "We believe that you should be exposed to perspectives from all sides, rather than just those of people who share similar opinions to yours. Additionally, we encourage you to follow great articles instead of following individuals.",
  },
  {
    question: "How can I save an article as a favorite and read it later?",
    answer:
      "Please leave a clever comment on it, and it will be saved under 'Your Comments.' You can then click the link to access it.",
  },
  {
    question: "How can I delete comments made by other users on my article?",
    answer:
      "Unfortunately, we don't offer the option to delete comments made by other users. We believe that it's important to allow diverse perspectives and foster open dialogue, even if the opinions shared differ from your own.",
  },
];

function Answer({ children }: Readonly<{ children: React.ReactNode }>) {
  return <div className="space-y-4">{children}</div>;
}

export default function FAQPage() {
  return (
    <div className="flex min-h-screen max-w-full flex-col overflow-x-hidden bg-[#e6e6e6] text-[#000000]">
      <SiteHeader />

      <main className="flex-1">
        <section className="border-b border-[#c4c4c4] bg-[#f7f7f7]">
          <div className="mx-auto grid w-full max-w-7xl gap-8 px-4 py-10 sm:px-6 sm:py-14 md:grid-cols-[minmax(0,1fr)_280px] md:items-center lg:grid-cols-[minmax(0,1fr)_360px] lg:px-8 lg:py-18">
            <div className="min-w-0 w-full max-w-[22rem] sm:max-w-none">
              <p className="text-sm font-semibold uppercase tracking-normal text-[#4d4d4d]">
                FAQ
              </p>
              <h1 className="mt-3 max-w-full break-words text-3xl font-semibold leading-tight tracking-normal text-[#000000] sm:max-w-4xl sm:text-5xl lg:text-6xl">
                Frequently asked questions for TownHallUS.com.
              </h1>
              <p className="mt-5 max-w-full break-words text-lg leading-8 text-[#1f1f1f] sm:max-w-3xl sm:text-xl sm:leading-9">
                Answers about accounts, voter status, political neutrality,
                usernames, avatars, posts, comments, and support.
              </p>
            </div>

            <aside
              aria-label="FAQ page details"
              className="min-w-0 w-full max-w-[22rem] border-l-0 border-[#999999] bg-[#eeeeee] p-5 shadow-[0_1px_2px_rgba(0,0,0,0.16)] sm:max-w-none md:border-l md:bg-transparent md:shadow-none"
            >
              <div className="flex items-center gap-4">
                <span className="flex size-16 items-center justify-center rounded-lg border border-[#999999] bg-[#ffffff]">
                  <CircleHelpIcon className="size-9 text-[#666666]" />
                </span>
                <div>
                  <p className="text-sm text-[#4d4d4d]">Page</p>
                  <p className="font-semibold text-[#000000]">
                    FREQUENTLY ASKED QUESTIONS (FAQ)
                  </p>
                </div>
              </div>

              <dl className="mt-6 divide-y divide-[#c4c4c4]">
                <div className="grid gap-1 py-3 text-sm sm:grid-cols-[96px_1fr] sm:gap-3">
                  <dt className="font-medium text-[#4d4d4d]">Updated</dt>
                  <dd className="min-w-0 break-words text-[#000000]">
                    September 12, 2025
                  </dd>
                </div>
                <div className="grid gap-1 py-3 text-sm sm:grid-cols-[96px_1fr] sm:gap-3">
                  <dt className="font-medium text-[#4d4d4d]">Version</dt>
                  <dd className="min-w-0 break-words text-[#000000]">1.0.2</dd>
                </div>
                <div className="grid gap-1 py-3 text-sm sm:grid-cols-[96px_1fr] sm:gap-3">
                  <dt className="font-medium text-[#4d4d4d]">Questions</dt>
                  <dd className="min-w-0 break-words text-[#000000]">
                    {faqs.length}
                  </dd>
                </div>
              </dl>
            </aside>
          </div>
        </section>

        <section className="bg-[#e6e6e6]">
          <div className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6 sm:py-12 lg:px-8 lg:py-14">
            <div className="grid gap-4">
              {faqs.map((faq, index) => (
                <details
                  key={faq.question}
                  className="group rounded-lg border border-[#c4c4c4] bg-[#f7f7f7] shadow-[0_1px_2px_rgba(0,0,0,0.12)] transition-shadow open:shadow-[0_3px_8px_rgba(0,0,0,0.16)]"
                  open={index === 0}
                >
                  <summary className="grid cursor-pointer list-none grid-cols-[40px_1fr_24px] gap-3 px-4 py-4 outline-none focus-visible:ring-3 focus-visible:ring-[#808080]/50 sm:grid-cols-[48px_1fr_24px] sm:gap-4 sm:px-5 sm:py-5 [&::-webkit-details-marker]:hidden">
                    <span className="flex size-10 items-center justify-center rounded-full bg-[#d1d1d1] text-sm font-semibold text-[#000000] sm:size-12">
                      {index + 1}
                    </span>
                    <span className="min-w-0 pt-1 text-base font-semibold leading-7 text-[#000000] sm:text-lg sm:leading-8">
                      {faq.question}
                    </span>
                    <ChevronDownIcon
                      className="mt-2 size-5 text-[#4d4d4d] transition-transform group-open:rotate-180"
                      aria-hidden="true"
                    />
                  </summary>
                  <div className="border-t border-[#c4c4c4] px-4 pb-5 pt-4 sm:px-5">
                    <div className="grid gap-3 sm:grid-cols-[48px_1fr] sm:gap-4">
                      <span className="hidden size-12 items-center justify-center rounded-lg border border-[#9333EA] bg-[#9333EA] sm:flex">
                        <MessageCircleReplyIcon
                          className="size-6 text-[#ffffff]"
                          aria-hidden="true"
                        />
                      </span>
                      <div className="min-w-0 text-base leading-7 text-[#1f1f1f] sm:text-lg sm:leading-8">
                        <Answer>{faq.answer}</Answer>
                      </div>
                    </div>
                  </div>
                </details>
              ))}
            </div>
          </div>
        </section>

        <section className="border-t border-[#c4c4c4] bg-[#eeeeee]">
          <div className="mx-auto flex w-full max-w-7xl flex-col gap-4 px-4 py-10 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8">
            <div className="flex min-w-0 items-center gap-4">
              <span className="flex size-12 shrink-0 items-center justify-center rounded-lg border border-[#999999] bg-[#f7f7f7]">
                <MailIcon className="size-6 text-[#4d4d4d]" />
              </span>
              <p className="min-w-0 text-base leading-7 text-[#000000] sm:text-lg">
                If you have more questions and cannot find the answers here,
                please email us at{" "}
                <a
                  href="mailto:support@townhallus.com"
                  className={contactLinkClassName}
                >
                  support@townhallus.com
                </a>
                .
              </p>
            </div>
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
